name: ðŸ› Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to report a bug!
        
        Before submitting, please:
        1. Check existing issues to avoid duplicates
        2. Review the [troubleshooting guide](https://github.com/CloudbrokerAz/hcp-terraform-onboarding/blob/main/.github/WORKFLOW-TROUBLESHOOTING.md)
        3. Ensure you're using the latest version

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is experiencing the issue?
      options:
        - tenant-config-project (Platform Team Layer)
        - bu-control-workspace (BU Team Layer)
        - Both modules
        - CI/CD Workflows
        - Documentation
        - Examples
        - Tests
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what occurred instead
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Configure module with...
        2. Run terraform apply...
        3. Observe error...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration Files
      description: Relevant Terraform or YAML configuration
      placeholder: Paste your configuration (remove sensitive data)
      render: hcl

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: Paste error output here
      render: shell

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Output of `terraform version`
      placeholder: "e.g., Terraform v1.6.0"
    validations:
      required: true

  - type: input
    id: provider-versions
    attributes:
      label: Provider Versions
      description: Relevant provider versions (TFE, GitHub, etc.)
      placeholder: "e.g., hashicorp/tfe v0.54.0, integrations/github v6.2.1"

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is this issue occurring?
      options:
        - Local Development
        - CI/CD Pipeline (GitHub Actions)
        - HCP Terraform
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - HCP Terraform organization size
        - Number of business units
        - Special network/firewall configurations
        - Custom modifications made

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severely does this bug impact your work?
      options:
        - Critical (Blocking production deployment)
        - High (Major functionality broken)
        - Medium (Feature partially working)
        - Low (Minor inconvenience)
    validations:
      required: true

  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have reviewed the troubleshooting documentation
          required: true
        - label: I have removed all sensitive information from examples
          required: true
        - label: I am using a supported Terraform version (>= 1.6.0)
          required: true
        - label: I can reproduce this issue consistently
          required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if found)
      description: Have you found any temporary workaround?
      placeholder: Describe any workaround you've discovered
