name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a new feature!
        
        Help us understand your use case and requirements.
        
        Before submitting:
        1. Check if a similar feature request exists
        2. Review the roadmap and existing functionality
        3. Consider if this can be achieved with existing features

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Platform Team Module (tenant-config-project)
        - BU Team Module (bu-control-workspace)
        - YAML Configuration Schema
        - CI/CD Workflows
        - Testing Framework
        - Documentation
        - Examples
        - Security/Compliance
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your proposed solution or feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered alternative solutions?
      placeholder: Describe any alternative approaches you've thought about

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        How would you use this feature in your workflow?
        Who else might benefit from this feature?
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Configuration
      description: Provide an example of how you'd use this feature
      placeholder: Show what the configuration might look like
      render: hcl

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No - Backward compatible"
        - "Yes - Would require migration"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking adoption)
        - High (Significantly improve workflow)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who would benefit from this feature?
      placeholder: |
        - Number of teams/users affected
        - Frequency of use
        - Impact on adoption
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: Select all that apply
      options:
        - label: New resource/module functionality
        - label: Enhanced YAML schema
        - label: Improved validation/error handling
        - label: Better documentation
        - label: Performance optimization
        - label: Security enhancement
        - label: Developer experience improvement
        - label: CI/CD workflow enhancement
        - label: Testing capability
        - label: Integration with external tools

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies or prerequisites?
      placeholder: |
        - Required provider features
        - External tool integrations
        - Terraform version requirements

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical considerations for implementation?
      placeholder: |
        - Suggested approach
        - Potential challenges
        - Required changes to existing code

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else we should know?
      placeholder: |
        - Related features
        - Industry best practices
        - Similar implementations in other tools
        - Community feedback

  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: I have reviewed the existing documentation
          required: true
        - label: I have considered if this can be achieved currently
          required: true
        - label: This feature aligns with the project's goals
          required: false
