bu: data_mgmt
projects:
  dm_prod:
    name: dm_prod
    description: production platform for data, integration, and service management
    environment: prod
    team_project_access:
      dm_maintain:
        team:
          access: "maintain"
      dm_write:
        team:
          access: "write"
    read-outputs:
      dm_team_prod:
        project: dm_team_prod
        access: read-outputs
  dm_nonprod:
    name: dm_nonprod
    description: non-production platform for data, integration, and service management
    environment: nonprod
    team_project_access:
      dm_maintain_nonprod:
        team:
          access: "maintain"
      dm_write_nonprod:
        team:
          access: "write"
    read-outputs:
      dm_team_nonprod:
        project: dm_team_nonprod
        access: read-outputs