bu: data_integration_service_management
projects:
  dism_prod:
    name: dism_prod
    description: production platform for data, integration, and service management
    environment: prod
    team_project_access:
      dism_maintain:
        team:
          access: "maintain"
      dism_write:
        team:
          access: "write"
    read-outputs:
      dism_team_prod:
        project: dism_team_prod
        access: read-outputs
  dism_nonprod:
    name: dism_nonprod
    description: non-production platform for data, integration, and service management
    environment: nonprod
    team_project_access:
      dism_maintain_nonprod:
        team:
          access: "maintain"
      dism_write_nonprod:
        team:
          access: "write"
    read-outputs:
      dism_team_nonprod:
        project: dism_team_nonprod
        access: read-outputs