bu: digi_deliv
projects:
  dd_prod:
    name: dd_prod
    description: production platform for digital delivery initiatives
    environment: prod
    team_project_access:
      dd_maintain:
        team:
          access: "maintain"
      dd_write:
        team:
          access: "write"
    read-outputs:
      dd_team_prod:
        project: dd_team_prod
        access: read-outputs
  dd_nonprod:
    name: dd_nonprod
    description: non-production platform for digital delivery staging and testing
    environment: nonprod
    team_project_access:
      dd_maintain_nonprod:
        team:
          access: "maintain"
      dd_write_nonprod:
        team:
          access: "write"
    read-outputs:
      dd_team_nonprod:
        project: dd_team_nonprod
        access: read-outputs