bu: digital_delivery
projects:
  delivery_prod:
    name: delivery_prod
    description: production platform for digital delivery initiatives
    environment: prod
    team_project_access:
      delivery_maintain:
        team:
          access: "maintain"
      delivery_write:
        team:
          access: "write"
    read-outputs:
      delivery_team_prod:
        project: delivery_team_prod
        access: read-outputs
  delivery_nonprod:
    name: delivery_nonprod
    description: non-production platform for digital delivery staging and testing
    environment: nonprod
    team_project_access:
      delivery_maintain_nonprod:
        team:
          access: "maintain"
      delivery_write_nonprod:
        team:
          access: "write"
    read-outputs:
      delivery_team_nonprod:
        project: delivery_team_nonprod
        access: read-outputs