bu: strat_arch
projects:
  sa_prod:
    name: sa_prod
    description: core production platform for strategy and architecture
    environment: prod
    team_project_access:
      sa_maintain:
        team:
          access: "maintain"
      sa_write:
        team:
          access: "write"
    read-outputs:
      sa_team_prod:
        project: sa_team_prod
        access: read-outputs
  sa_nonprod:
    name: sa_nonprod
    description: non-production platform for strategy development and testing
    environment: nonprod
    team_project_access:
      sa_maintain_nonprod:
        team:
          access: "maintain"
      sa_write_nonprod:
        team:
          access: "write"
    read-outputs:
      sa_team_nonprod:
        project: sa_team_nonprod
        access: read-outputs